### ISSUE TITLE
License for this template

### ISSUE THREAD

**Issue by abinash2512** [christopher-caldwell/vite-material-ui#10]
Hi,

I was wondering what license is this template issued under? Would I be able to use it in my non-commercial educational project?

Thanks in advance

**Comment by christopher-caldwell** [comment]
Whatever the least restrictive one is. I think that's [Unlicensed](https://choosealicense.com/licenses/unlicense/), but I think MIT would work as well. 

Any thoughts? I am not very familiar with the differences. It's completely open to use however you want.

**Comment by abinash2512** [comment]
Thank you. I think the least restrictive license is MIT, I'm not sure if Unlicensed counts as a license per say for educational purposes.
