### ISSUE TITLE
Theme might be use invalid color format

### ISSUE THREAD

**Issue by NaClYen** [christopher-caldwell/vite-material-ui#4]
## error

The `#fffff` (with 5 times `f`) cause this issue:
![image](https://user-images.githubusercontent.com/10209536/145529692-cc5af9e4-d9ff-4751-a7ff-3651c82a1a0c.png)

It makes lots of component backgrounds to be transparent. (dropdown, dialog...etc)

## code

When I modified this...
https://github.com/christopher-caldwell/vite-material-ui/blob/b651a2988e0ce1bfc470d6904dbc02b4708a1b51/src/providers/Theme.tsx#L27

that to `#ffffff`, everything works well as I expect.

**Comment by christopher-caldwell** [comment]
Good catch, thanks!
